---
version: '3'
services:
  mexc:
    container_name: mexc
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
        - "./mexc.log:/mexc.log"
    environment:
      - TOKEN=${TOKEN}
      - KEY=${KEY}
      - SECRET=${SECRET}