# Generated by Django 4.2.10 on 2024-02-17 13:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('ticker', models.CharField(max_length=30)),
                ('size', models.FloatField()),
                ('price', models.FloatField()),
                ('risk', models.FloatField()),
                ('date', models.DateTimeField(verbose_name=datetime.datetime(2024, 2, 17, 13, 5, 36, 42095, tzinfo=datetime.timezone.utc))),
            ],
        ),
    ]
