---
version: '3'
services:
  bitmart:
    # image: freqtradeorg/freqtrade:stable
    # image: freqtradeorg/freqtrade:develop
    image: freqtradeorg/freqtrade:develop_plot
    # build:
    #   context: .
    #   dockerfile: "./docker/Dockerfile.custom"
    restart: unless-stopped
    container_name: bitmart
    volumes:
      - "./user_data:/freqtrade/user_data"
    ports:
      - "127.0.0.1:8080:8080"
    command: >
      trade
      --logfile /freqtrade/user_data/logs/bitmart.log
      --db-url sqlite:////freqtrade/user_data/tradesv3_bitmart.sqlite
      --config /freqtrade/user_data/configBitmart.json
      --strategy LS
  # mexc:
  #   # image: freqtradeorg/freqtrade:stable
  #   # image: freqtradeorg/freqtrade:develop
  #   image: freqtradeorg/freqtrade:develop_plot
  #   # build:
  #   #   context: .
  #   #   dockerfile: "./docker/Dockerfile.custom"
  #   restart: unless-stopped
  #   container_name: mexc
  #   volumes:
  #     - "./user_data:/freqtrade/user_data"
  #   ports:
  #     - "127.0.0.1:8081:8081"
  #   command: >
  #     trade
  #     --logfile /freqtrade/user_data/logs/mexc.log
  #     --db-url sqlite:////freqtrade/user_data/tradesv3_mexc.sqlite
  #     --config /freqtrade/user_data/configMEXC.json
  #     --strategy LS
